### ISSUE TITLE
Rust: `lsp-find-definition` not working for functions with proc-macro attribute

### ISSUE THREAD

**Issue by DerickEddington** [emacs-lsp/lsp-mode#3504]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When a Rust function definition has a proc-macro attribute applied to it, and with point on a call to such a function, `lsp-find-definition` (or `xref-find-definitions`) does not jump to the definition but instead just prints in the `*Messages*` buffer the message: "LSP :: Not found for:" (or "xref--not-found-error: No definitions found for:").

Similarly, the "highlighting of the same symbol" feature does not work either, for such functions, when point is on them.

These previously worked, with the `20220330` version (I think it was) of `lsp-mode` from MELPA, and with `rust-analyzer` version `2022-03-28`.

If the proc-macro attribute is commented-out, then these features do work.

With Visual Studio Code `1.66.2`, with the latest `matklad.rust-analyzer` extension versions (`v0.2.1040` or `v0.3.1041`, `5/2/2022`), the analogous features do work.  I.e. pressing `F12` with the cursor on the same function-call in the same file does jump to the function's definition, even when it has a proc-macro attribute, and same-symbol highlighting does work.  I think this shows that the problem is not in `rust-analyzer`.

#### `src/lib.rs`
```rust
#[derive(Debug)]
pub struct Thing;

impl Thing {
    #[tracing::instrument]
    fn a(&self) {}

    #[minimal_attribute_proc_macro::identity]
    fn b(&self) {}
}

pub fn hmm() {
    Thing.a();  // With point on "a", `lsp-find-definition` does not work.
    Thing.b();  // Ditto for "b".
}
```

#### `Cargo.toml`
```toml
[package]
name = "applied_attribute_proc_macro"
version = "0.0.0"
edition = "2021"

[dependencies]
tracing = "0.1"
minimal_attribute_proc_macro = { path = "minimal_attribute_proc_macro" }
```

#### `minimal_attribute_proc_macro/src/lib.rs`
```rust
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn identity(_args: TokenStream, item: TokenStream) -> TokenStream {
    item
}
```

#### `minimal_attribute_proc_macro/Cargo.toml`
```toml
[package]
name = "minimal_attribute_proc_macro"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true
```

### Expected behavior

`lsp-find-definition` (and `xref-find-definitions`), and "highlighting of the same symbol", should work like it previously did, when a function definition has a proc-macro attribute.

### Which Language Server did you use?

`rust-analyzer` versions `2022-05-02` and `nightly`.

### OS

Linux

### Anything else?

I'm using NixOS `21.11`, Emacs `27.2` and `28.1`, and the latest MELPA packages (including for dependencies) which provides `lsp-mode` `20220502.459` (commit `f7b363`).
