### ISSUE TITLE
golangci-lint v2 flags have changed

### ISSUE THREAD

**Issue by offbyone** [emacs-lsp/lsp-mode#4781]
### Thank you for the bug report

- [x] I am using the latest version of `lsp-mode` related packages.
- [x] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [x] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

The flags defined in `clients/lsp-golangci-lint.el` are not compatible with v2 of `golangci-lint`: 

```
(defun lsp-golangci-lint--get-initialization-options ()
  "Return initialization options for golangci-lint-langserver."
  (let ((opts (make-hash-table :test 'equal))
        (command (vconcat `(,lsp-golangci-lint-path)
                          ["run" "--out-format=json" "--issues-exit-code=1"]
                          (lsp-golangci-lint--run-args))))
    (puthash "command" command opts)
    opts))
```

The flag to output json has changed to `--output.json.path=stdout`: https://github.com/golangci/golangci-lint/discussions/5612

### Steps to reproduce

1. upgrade golangcli-lint to v2
2. enable the LSP

### Expected behavior

It should work

### Which Language Server did you use?

golangci-lint

### OS

MacOS

### Error callstack

```emacs-lisp
There's no error, it reports as a flycheck error
```

**Comment by Z01d-b3rg** [comment]
Had the same issue and was able to fix it by changing the initialization options to the following:
```elisp
(defun lsp-golangci-lint--get-initialization-options ()
  "Return initialization options for golangci-lint-langserver."
  (let ((opts (make-hash-table :test 'equal))
        (command (vconcat `(,lsp-golangci-lint-path)
                          ["run" "--output.json.path" "stdout" "--show-stats=false" "--issues-exit-code=1"]
                          (lsp-golangci-lint--run-args))))
    (puthash "command" command opts)
    opts))

```

And when using golangci configuration files not located in the repository root, I had to also configure the `relative-path-mode`
```yaml
# file: .golangci.yaml
run:
  # The mode used to evaluate relative paths.
  # It's used by exclusions, Go plugins, and some linters.
  # The value can be:
  # - `gomod`: the paths will be relative to the directory of the `go.mod` file.
  # - `gitroot`: the paths will be relative to the git root (the parent directory of `.git`).
  # - `cfg`: the paths will be relative to the configuration file.
  # - `wd` (NOT recommended): the paths will be relative to the place where golangci-lint is run.
  # Default: cfg
  relative-path-mode: gitroot
```
